### ISSUE TITLE
Test sensorer på Laksetorvet

### ISSUE THREAD

**Issue by tna-randers** [Randers-Kommune-Digitalisering/vis-os2iot-data#12]

**Comment by st-randers** [comment]
Test af rengøringssensor/aktivitetssensor på laksetorvet

**Comment by st-randers** [comment]
Rengøringssensor er testet, total antal "intrusions" tælles. Kan ses i [OS2IoT PIR motion sensor table](https://superset.prototypes.randers.dk/explore/?dashboard_page_id=iDsgDTUE4&slice_id=114)
