### ISSUE TITLE
Opsætning af vandmåler-sensorer på skole - flyt indendørs antenne midlertidigt til test

### ISSUE THREAD

**Issue by tna-randers** [Randers-Kommune-Digitalisering/vis-os2iot-data#8]

**Comment by st-randers** [comment]
Grønhøjskolen SFO:
KV Vandmåler: 04B64819 - 55488106
Varmemåler: 6ZRI8911107284
El-måler:23420722

Laksetorvet: 
KV Vandmåler:04B64819 - 56291952
VV Vandmåler:04B64819 - 56860032
Varmemåler:6ZRI8911107282

Co2 sensor:
E 1.36 bliver til køkken Laksetorvet C 2.01
E 0.27 bliver til Center Åbakken Hovedteknik
Tidl. kantine bliver til Grønhøjskolen Hovedteknik
